# Generated by Django 3.0.5 on 2022-12-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherupdates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityWeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('icon', models.TextField()),
                ('temperature', models.TextField()),
                ('country_code', models.CharField(max_length=10)),
                ('wind', models.TextField()),
                ('humidity', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='CityWeather',
        ),
    ]
